name: Third Party Libraries Modification Testing

on:
  pull_request:
    branches:
      - trunk
      - "3.[89]"
      - "[4-9].[0-9]"

jobs:
  get-third-party-changed-files:
    runs-on: ubuntu-latest
    name: Get changed files
    permissions:
      pull-requests: read
    outputs:
       third_party_libraries: ${{ steps.modified_third_party_libraries.outputs.third_party_libraries }}
    steps:
        - name: Get changed files
          id: changed_files
          uses: tj-actions/changed-files@v37

        - name: Get modified third party libraries
          id: modified_third_party_libraries
          run: |
            MODIFIED_FILES="${{ steps.changed_files.outputs.all_changed_files }}"
            THIRD_PARTY_LIBRARIES=(
              "src/wp-includes/ID3"
              "src/wp-includes/IXR"
              "src/wp-includes/PHPMailer"
              "src/wp-includes/Requests"
              "src/wp-includes/SimplePie"
              "src/wp-includes/sodium_compat"
              "src/wp-includes/Text"
            )
            MODIFIED_THIRD_PARTY_LIBRARIES=()
            for LIBRARY in "${THIRD_PARTY_LIBRARIES[@]}"; do
              if [[ "${MODIFIED_FILES}" == *"${LIBRARY}"* ]]; then
                MODIFIED_THIRD_PARTY_LIBRARIES+=("${LIBRARY}")
              fi
            done
            echo "third_party_libraries=${MODIFIED_THIRD_PARTY_LIBRARIES[*]}" >> $GITHUB_OUTPUT

  comment-third-party-changed-files:
    needs: get-third-party-changed-files
    runs-on: ubuntu-latest
    name: Comment on third party libraries changes
    permissions:
      pull-requests: write

    steps:
        - name: Comment on third party libraries changed_files
          run: echo ${{ needs.get-third-party-changed-files.outputs.third_party_libraries }}