name: Third Party Libraries Modification Testing

on:
  pull_request:
    branches:
      - trunk
      - '3.[89]'
      - '[4-9].[0-9]'

jobs:
  comment-on-modified-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List modified files
        id: files
        run: |
          echo "::set-output name=modified_files::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})"

      - name: Check if files modified under specific directories
        id: directories
        run: |
          MODIFIED_FILES="${{ steps.files.outputs.modified_files }}"
          DIRECTORIES=(
            "src/wp-includes/ID3"
            "src/wp-includes/IXR"
            "src/wp-includes/PHPMailer"
            "src/wp-includes/Requests"
            "src/wp-includes/SimplePie"
            "src/wp-includes/sodium_compat"
            "src/wp-includes/Text"
          )
          for DIR in "${DIRECTORIES[@]}"; do
            if echo "${MODIFIED_FILES}" | grep -q "^${DIR}/"; then
              echo "::set-output name=comment_message::Files modified under directory: ${DIR}"
              break
            fi
          done

      - name: Comment on modified files
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.directories.outputs.comment_message }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}