name: Third Party Libraries Modification Testing

on:
  pull_request:
    branches:
      - trunk
      - "3.[89]"
      - "[4-9].[0-9]"

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    name: Get changed files
    permissions:
      pull-requests: read

    steps:
        - name: Get changed files
          id: changed_files
          uses: tj-actions/changed-files@v37

        - name: Print changed files
          run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done